const SoLshops = {
    "Bai Hui Hall": {
        "eat immediately": true,
        "description": L('Bai Hui HallDesc'),
        cn_name: L('Bai Hui Hall'),
        emoji: '🍚',
        "items": [
            { "label": L('BHHlable1') },
            { "label": L('fried egg'), "type": "food", "item": "fried egg" },
            { "label": L('boiled egg'), "type": "food", "item": "boiled egg" },
            { "label": L('rice'), "type": "food", "item": "rice" },
            { "label": L('chicken soup'), "type": "food", "item": "chicken soup" },
            { "label": L('lentil soup'), "type": "food", "item": "lentil soup" },
            { "label": L('egg sandwich'), "type": "food", "item": "egg sandwich" },
            { "label": L('chicken sandwich'), "type": "food", "item": "chicken sandwich" },
            { "label": L('grilled cheese'), "type": "food", "item": "grilled cheese" },


            { "label": L('BHHlable2') },
            { "label": L('fried rice'), "type": "food", "item": "fried rice" },
            { "label": L('Scrambled eggs with tomatoes'), "type": "food", "item": "Scrambled eggs with tomatoes" },
            { "label": L('Char Siu'), "type": "food", "item": "Char Siu" },
            { "label": L('Gyudon'), "type": "food", "item": "Gyudon" },
            { "label": L('Shrimp Tempura'), "type": "food", "item": "Shrimp Tempura" },
            { "label": L('fried tofu'), "type": "food", "item": "fried tofu" },
            { "label": L('chicken dumplings'), "type": "food", "item": "chicken dumplings" },
            { "label": L('beef dumplings'), "type": "food", "item": "beef dumplings" },
            { "label": L('pork dumplings'), "type": "food", "item": "pork dumplings" },
            { "label": L('Wonton'), "type": "food", "item": "Wonton" },

            { "label": L('BHHlable3') },
            { "label": L('apple pie'), "type": "food", "item": "apple pie" },
            { "label": L('chocolate pie'), "type": "food", "item": "chocolate pie" },
            { "label": L('cracker'), "type": "food", "item": "cracker" },
            { "label": L('chocolate roll'), "type": "food", "item": "chocolate roll" },
            { "label": L('caramel apple'), "type": "food", "item": "caramel apple" },
            { "label": L('donut'), "type": "food", "item": "donut" },
            { "label": L('chocolate donut'), "type": "food", "item": "chocolate donut" },

            { "label": L('BHHlable4') },
            { "label": L('cup of water'), "type": "food", "item": "cup of water" },
            { "label": L('cup of cola'), "type": "food", "item": "cup of cola" },
            { "label": L('cup of coffee'), "type": "food", "item": "cup of coffee" },
            { "label": L('cup of tea'), "type": "food", "item": "cup of tea" },
        ]
    },
    "JT Ult Fresh": {
        "description": L('JT Ult FreshDesc'),
        cn_name: "约特鲜生",
        emoji: '🥦',
        "items": [
            { "label": L('JUFlabel1') },
            { "label": L('tomato'), "type": "food", "item": "tomato" },
            { "label": L('lettuce'), "type": "food", "item": "lettuce" },
            { "label": L('cucumber'), "type": "food", "item": "cucumber" },
            { "label": L('bell pepper'), "type": "food", "item": "bell pepper" },
            { "label": L('eggplant'), "type": "food", "item": "eggplant" },
            { "label": L('basil'), "type": "food", "item": "basil" },
            { "label": L('parsley'), "type": "food", "item": "parsley" },
            { "label": L('potato'), "type": "food", "item": "potato" },
            { "label": L('zucchini'), "type": "food", "item": "zucchini" },
            { "label": L('onion'), "type": "food", "item": "onion" },
            { "label": L('garlic'), "type": "food", "item": "garlic" },
            { "label": L('cabbage'), "type": "food", "item": "cabbage" },
            { "label": L('scallion'), "type": "food", "item": "scallion" },
            { "label": L('apple'), "type": "food", "item": "apple" },
            { "label": L('JUFlabel2') },
            { "label": L('eggs'), "type": "food", "item": "eggs" },
            { "label": L('raw beef'), "type": "food", "item": "raw beef" },
            { "label": L('raw pork'), "type": "food", "item": "raw pork" },
            { "label": L('raw fish'), "type": "food", "item": "raw fish" },
            { "label": L('shrimp'), "type": "food", "item": "shrimp" },
            { "label": L('tofu'), "type": "food", "item": "tofu" },
            { "label": L('JUFlabel3') },
            { "label": L('noodles'), "type": "food", "item": "noodles" },
            { "label": L('pasta'), "type": "food", "item": "pasta" },
            { "label": L('flour'), "type": "food", "item": "flour" },
            { "label": L('wheat dough'), "type": "food", "item": "wheat dough" },
            { "label": L('raw rice'), "type": "food", "item": "raw rice" },
            { "label": L('cream'), "type": "food", "item": "cream" },
            { "label": L('chocolate'), "type": "food", "item": "chocolate" },
            { "label": L('JUFlabel4') },
            { "label": L('salt'), "type": "food", "item": "salt" },
            { "label": L('sugar'), "type": "food", "item": "sugar" },
            { "label": L('oil'), "type": "food", "item": "oil" },
            { "label": L('soy sauce'), "type": "food", "item": "soy sauce" },
            { "label": L('hoisin sauce'), "type": "food", "item": "hoisin sauce" },
            { "label": L('five spice'), "type": "food", "item": "five spice" },
            { "label": L('butter'), "type": "food", "item": "butter" }
        ]
    },

}
Object.assign(setup.Shops.db, SoLshops)